// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type BedManagement struct {
	ID         uuid.UUID
	BedID      uuid.UUID
	PatientID  uuid.UUID
	Status     interface{}
	AssignedAt sql.NullTime
	UpdatedAt  sql.NullTime
}

type Donor struct {
	ID               uuid.UUID
	FullName         string
	Email            string
	Password         string
	Address          string
	PhoneNumber      string
	Gender           interface{}
	BirthDate        time.Time
	BloodGroup       interface{}
	Weight           int16
	HealthCondition  interface{}
	LastDonation     sql.NullTime
	DonationCount    sql.NullInt32
	LastCheckupDate  sql.NullTime
	DonationLocation sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
	DeletedAt        sql.NullTime
}
