// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: protos/nurse-service/nurse-service.proto

package nursepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BedStatus int32

const (
	BedStatus_BED_AVAILABLE   BedStatus = 0
	BedStatus_BED_OCCUPIED    BedStatus = 1
	BedStatus_BED_RESERVED    BedStatus = 2
	BedStatus_BED_MAINTENANCE BedStatus = 3
)

// Enum value maps for BedStatus.
var (
	BedStatus_name = map[int32]string{
		0: "BED_AVAILABLE",
		1: "BED_OCCUPIED",
		2: "BED_RESERVED",
		3: "BED_MAINTENANCE",
	}
	BedStatus_value = map[string]int32{
		"BED_AVAILABLE":   0,
		"BED_OCCUPIED":    1,
		"BED_RESERVED":    2,
		"BED_MAINTENANCE": 3,
	}
)

func (x BedStatus) Enum() *BedStatus {
	p := new(BedStatus)
	*p = x
	return p
}

func (x BedStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BedStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_nurse_service_nurse_service_proto_enumTypes[0].Descriptor()
}

func (BedStatus) Type() protoreflect.EnumType {
	return &file_protos_nurse_service_nurse_service_proto_enumTypes[0]
}

func (x BedStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BedStatus.Descriptor instead.
func (BedStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{0}
}

type PatientDonor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email            string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password         string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Address          string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber      string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Gender           string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthDate        string                 `protobuf:"bytes,8,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	BloodGroup       string                 `protobuf:"bytes,9,opt,name=blood_group,json=bloodGroup,proto3" json:"blood_group,omitempty"`
	LastDonation     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=last_donation,json=lastDonation,proto3" json:"last_donation,omitempty"`
	DonationCount    int32                  `protobuf:"varint,11,opt,name=donation_count,json=donationCount,proto3" json:"donation_count,omitempty"`
	IsEligible       bool                   `protobuf:"varint,12,opt,name=is_eligible,json=isEligible,proto3" json:"is_eligible,omitempty"`
	LastCheckupDate  *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_checkup_date,json=lastCheckupDate,proto3" json:"last_checkup_date,omitempty"`
	Weight           float64                `protobuf:"fixed64,14,opt,name=weight,proto3" json:"weight,omitempty"`
	HealthConditions string                 `protobuf:"bytes,15,opt,name=health_conditions,json=healthConditions,proto3" json:"health_conditions,omitempty"`
	DonationLocation string                 `protobuf:"bytes,16,opt,name=donation_location,json=donationLocation,proto3" json:"donation_location,omitempty"`
	Timestamps       *Timestamps3           `protobuf:"bytes,17,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
}

func (x *PatientDonor) Reset() {
	*x = PatientDonor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PatientDonor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientDonor) ProtoMessage() {}

func (x *PatientDonor) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientDonor.ProtoReflect.Descriptor instead.
func (*PatientDonor) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{0}
}

func (x *PatientDonor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PatientDonor) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *PatientDonor) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PatientDonor) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PatientDonor) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PatientDonor) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *PatientDonor) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *PatientDonor) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *PatientDonor) GetBloodGroup() string {
	if x != nil {
		return x.BloodGroup
	}
	return ""
}

func (x *PatientDonor) GetLastDonation() *timestamppb.Timestamp {
	if x != nil {
		return x.LastDonation
	}
	return nil
}

func (x *PatientDonor) GetDonationCount() int32 {
	if x != nil {
		return x.DonationCount
	}
	return 0
}

func (x *PatientDonor) GetIsEligible() bool {
	if x != nil {
		return x.IsEligible
	}
	return false
}

func (x *PatientDonor) GetLastCheckupDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheckupDate
	}
	return nil
}

func (x *PatientDonor) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PatientDonor) GetHealthConditions() string {
	if x != nil {
		return x.HealthConditions
	}
	return ""
}

func (x *PatientDonor) GetDonationLocation() string {
	if x != nil {
		return x.DonationLocation
	}
	return ""
}

func (x *PatientDonor) GetTimestamps() *Timestamps3 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type Bed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BedNumber   int64        `protobuf:"varint,2,opt,name=bed_number,json=bedNumber,proto3" json:"bed_number,omitempty"`
	BedType     string       `protobuf:"bytes,3,opt,name=bed_type,json=bedType,proto3" json:"bed_type,omitempty"`
	Description string       `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status      BedStatus    `protobuf:"varint,5,opt,name=status,proto3,enum=BedStatus" json:"status,omitempty"`
	Timestamps  *Timestamps3 `protobuf:"bytes,6,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
}

func (x *Bed) Reset() {
	*x = Bed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bed) ProtoMessage() {}

func (x *Bed) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bed.ProtoReflect.Descriptor instead.
func (*Bed) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{1}
}

func (x *Bed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bed) GetBedNumber() int64 {
	if x != nil {
		return x.BedNumber
	}
	return 0
}

func (x *Bed) GetBedType() string {
	if x != nil {
		return x.BedType
	}
	return ""
}

func (x *Bed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Bed) GetStatus() BedStatus {
	if x != nil {
		return x.Status
	}
	return BedStatus_BED_AVAILABLE
}

func (x *Bed) GetTimestamps() *Timestamps3 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

// ---------------- Donor CRUD ----------------
// CREATE
type CreateDonorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullName         string  `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email            string  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password         string  `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Address          string  `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber      string  `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Gender           string  `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthDate        string  `protobuf:"bytes,7,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	BloodGroup       string  `protobuf:"bytes,8,opt,name=blood_group,json=bloodGroup,proto3" json:"blood_group,omitempty"`
	Weight           float64 `protobuf:"fixed64,9,opt,name=weight,proto3" json:"weight,omitempty"`
	HealthConditions string  `protobuf:"bytes,10,opt,name=health_conditions,json=healthConditions,proto3" json:"health_conditions,omitempty"`
}

func (x *CreateDonorRequest) Reset() {
	*x = CreateDonorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDonorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDonorRequest) ProtoMessage() {}

func (x *CreateDonorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDonorRequest.ProtoReflect.Descriptor instead.
func (*CreateDonorRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDonorRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateDonorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateDonorRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateDonorRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateDonorRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CreateDonorRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateDonorRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *CreateDonorRequest) GetBloodGroup() string {
	if x != nil {
		return x.BloodGroup
	}
	return ""
}

func (x *CreateDonorRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateDonorRequest) GetHealthConditions() string {
	if x != nil {
		return x.HealthConditions
	}
	return ""
}

type CreateDonorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Donor *PatientDonor `protobuf:"bytes,1,opt,name=donor,proto3" json:"donor,omitempty"`
}

func (x *CreateDonorResponse) Reset() {
	*x = CreateDonorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateDonorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDonorResponse) ProtoMessage() {}

func (x *CreateDonorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDonorResponse.ProtoReflect.Descriptor instead.
func (*CreateDonorResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateDonorResponse) GetDonor() *PatientDonor {
	if x != nil {
		return x.Donor
	}
	return nil
}

// GET BY ID
type GetDonorByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetDonorByIdRequest) Reset() {
	*x = GetDonorByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDonorByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonorByIdRequest) ProtoMessage() {}

func (x *GetDonorByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonorByIdRequest.ProtoReflect.Descriptor instead.
func (*GetDonorByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetDonorByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDonorByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Donor *PatientDonor `protobuf:"bytes,1,opt,name=donor,proto3" json:"donor,omitempty"`
}

func (x *GetDonorByIdResponse) Reset() {
	*x = GetDonorByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDonorByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDonorByIdResponse) ProtoMessage() {}

func (x *GetDonorByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDonorByIdResponse.ProtoReflect.Descriptor instead.
func (*GetDonorByIdResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetDonorByIdResponse) GetDonor() *PatientDonor {
	if x != nil {
		return x.Donor
	}
	return nil
}

// LIST
type ListDonorsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search       string `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"` // name, email
	Gender       string `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"` // filter (example: Male/Female)
	BloodGroup   string `protobuf:"bytes,3,opt,name=blood_group,json=bloodGroup,proto3" json:"blood_group,omitempty"`
	OnlyEligible bool   `protobuf:"varint,4,opt,name=only_eligible,json=onlyEligible,proto3" json:"only_eligible,omitempty"`
	Page         int32  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	Limit        int32  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListDonorsRequest) Reset() {
	*x = ListDonorsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDonorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDonorsRequest) ProtoMessage() {}

func (x *ListDonorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDonorsRequest.ProtoReflect.Descriptor instead.
func (*ListDonorsRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListDonorsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListDonorsRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *ListDonorsRequest) GetBloodGroup() string {
	if x != nil {
		return x.BloodGroup
	}
	return ""
}

func (x *ListDonorsRequest) GetOnlyEligible() bool {
	if x != nil {
		return x.OnlyEligible
	}
	return false
}

func (x *ListDonorsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListDonorsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDonorsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patients   []*PatientDonor `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
	TotalCount int32           `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListDonorsResponse) Reset() {
	*x = ListDonorsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDonorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDonorsResponse) ProtoMessage() {}

func (x *ListDonorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDonorsResponse.ProtoReflect.Descriptor instead.
func (*ListDonorsResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListDonorsResponse) GetPatients() []*PatientDonor {
	if x != nil {
		return x.Patients
	}
	return nil
}

func (x *ListDonorsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// UPDATE
type UpdateDonorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string  `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Email            string  `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password         string  `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Address          string  `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	PhoneNumber      string  `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Gender           string  `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	BirthDate        string  `protobuf:"bytes,8,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	BloodGroup       string  `protobuf:"bytes,9,opt,name=blood_group,json=bloodGroup,proto3" json:"blood_group,omitempty"`
	Weight           float64 `protobuf:"fixed64,10,opt,name=weight,proto3" json:"weight,omitempty"`
	HealthConditions string  `protobuf:"bytes,11,opt,name=health_conditions,json=healthConditions,proto3" json:"health_conditions,omitempty"`
}

func (x *UpdateDonorRequest) Reset() {
	*x = UpdateDonorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDonorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDonorRequest) ProtoMessage() {}

func (x *UpdateDonorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDonorRequest.ProtoReflect.Descriptor instead.
func (*UpdateDonorRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDonorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateDonorRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateDonorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateDonorRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateDonorRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateDonorRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *UpdateDonorRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UpdateDonorRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *UpdateDonorRequest) GetBloodGroup() string {
	if x != nil {
		return x.BloodGroup
	}
	return ""
}

func (x *UpdateDonorRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *UpdateDonorRequest) GetHealthConditions() string {
	if x != nil {
		return x.HealthConditions
	}
	return ""
}

type UpdateDonorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Donor *PatientDonor `protobuf:"bytes,1,opt,name=donor,proto3" json:"donor,omitempty"`
}

func (x *UpdateDonorResponse) Reset() {
	*x = UpdateDonorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDonorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDonorResponse) ProtoMessage() {}

func (x *UpdateDonorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDonorResponse.ProtoReflect.Descriptor instead.
func (*UpdateDonorResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDonorResponse) GetDonor() *PatientDonor {
	if x != nil {
		return x.Donor
	}
	return nil
}

// DELETE
type DeleteDonorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteDonorRequest) Reset() {
	*x = DeleteDonorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDonorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDonorRequest) ProtoMessage() {}

func (x *DeleteDonorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDonorRequest.ProtoReflect.Descriptor instead.
func (*DeleteDonorRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDonorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDonorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 204 = deleted
}

func (x *DeleteDonorResponse) Reset() {
	*x = DeleteDonorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDonorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDonorResponse) ProtoMessage() {}

func (x *DeleteDonorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDonorResponse.ProtoReflect.Descriptor instead.
func (*DeleteDonorResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteDonorResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// Register a new donation
type RegisterDonationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DonorId          string `protobuf:"bytes,1,opt,name=donor_id,json=donorId,proto3" json:"donor_id,omitempty"`
	DonationLocation string `protobuf:"bytes,2,opt,name=donation_location,json=donationLocation,proto3" json:"donation_location,omitempty"`
}

func (x *RegisterDonationRequest) Reset() {
	*x = RegisterDonationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDonationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDonationRequest) ProtoMessage() {}

func (x *RegisterDonationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDonationRequest.ProtoReflect.Descriptor instead.
func (*RegisterDonationRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{12}
}

func (x *RegisterDonationRequest) GetDonorId() string {
	if x != nil {
		return x.DonorId
	}
	return ""
}

func (x *RegisterDonationRequest) GetDonationLocation() string {
	if x != nil {
		return x.DonationLocation
	}
	return ""
}

type RegisterDonationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastDonation  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_donation,json=lastDonation,proto3" json:"last_donation,omitempty"`
	DonationCount int32                  `protobuf:"varint,2,opt,name=donation_count,json=donationCount,proto3" json:"donation_count,omitempty"`
	IsEligible    bool                   `protobuf:"varint,3,opt,name=is_eligible,json=isEligible,proto3" json:"is_eligible,omitempty"`
}

func (x *RegisterDonationResponse) Reset() {
	*x = RegisterDonationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDonationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDonationResponse) ProtoMessage() {}

func (x *RegisterDonationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDonationResponse.ProtoReflect.Descriptor instead.
func (*RegisterDonationResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{13}
}

func (x *RegisterDonationResponse) GetLastDonation() *timestamppb.Timestamp {
	if x != nil {
		return x.LastDonation
	}
	return nil
}

func (x *RegisterDonationResponse) GetDonationCount() int32 {
	if x != nil {
		return x.DonationCount
	}
	return 0
}

func (x *RegisterDonationResponse) GetIsEligible() bool {
	if x != nil {
		return x.IsEligible
	}
	return false
}

// Register medical checkup
type RegisterCheckupRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DonorId string `protobuf:"bytes,1,opt,name=donor_id,json=donorId,proto3" json:"donor_id,omitempty"`
}

func (x *RegisterCheckupRequest) Reset() {
	*x = RegisterCheckupRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCheckupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCheckupRequest) ProtoMessage() {}

func (x *RegisterCheckupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCheckupRequest.ProtoReflect.Descriptor instead.
func (*RegisterCheckupRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{14}
}

func (x *RegisterCheckupRequest) GetDonorId() string {
	if x != nil {
		return x.DonorId
	}
	return ""
}

type RegisterCheckupResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LastCheckupDate *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_checkup_date,json=lastCheckupDate,proto3" json:"last_checkup_date,omitempty"`
	IsEligible      bool                   `protobuf:"varint,2,opt,name=is_eligible,json=isEligible,proto3" json:"is_eligible,omitempty"`
}

func (x *RegisterCheckupResponse) Reset() {
	*x = RegisterCheckupResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterCheckupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterCheckupResponse) ProtoMessage() {}

func (x *RegisterCheckupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterCheckupResponse.ProtoReflect.Descriptor instead.
func (*RegisterCheckupResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterCheckupResponse) GetLastCheckupDate() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCheckupDate
	}
	return nil
}

func (x *RegisterCheckupResponse) GetIsEligible() bool {
	if x != nil {
		return x.IsEligible
	}
	return false
}

// ---------------- Bed Management----------------
// ASSIGN
type AssignPatientToBedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BedId     string `protobuf:"bytes,1,opt,name=bed_id,json=bedId,proto3" json:"bed_id,omitempty"`
	PatientId string `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
}

func (x *AssignPatientToBedRequest) Reset() {
	*x = AssignPatientToBedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignPatientToBedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPatientToBedRequest) ProtoMessage() {}

func (x *AssignPatientToBedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPatientToBedRequest.ProtoReflect.Descriptor instead.
func (*AssignPatientToBedRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{16}
}

func (x *AssignPatientToBedRequest) GetBedId() string {
	if x != nil {
		return x.BedId
	}
	return ""
}

func (x *AssignPatientToBedRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type AssignPatientToBedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bed *Bed `protobuf:"bytes,1,opt,name=bed,proto3" json:"bed,omitempty"`
}

func (x *AssignPatientToBedResponse) Reset() {
	*x = AssignPatientToBedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignPatientToBedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignPatientToBedResponse) ProtoMessage() {}

func (x *AssignPatientToBedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignPatientToBedResponse.ProtoReflect.Descriptor instead.
func (*AssignPatientToBedResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{17}
}

func (x *AssignPatientToBedResponse) GetBed() *Bed {
	if x != nil {
		return x.Bed
	}
	return nil
}

// RELEASE
type ReleaseBedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BedId string `protobuf:"bytes,1,opt,name=bed_id,json=bedId,proto3" json:"bed_id,omitempty"`
}

func (x *ReleaseBedRequest) Reset() {
	*x = ReleaseBedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseBedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseBedRequest) ProtoMessage() {}

func (x *ReleaseBedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseBedRequest.ProtoReflect.Descriptor instead.
func (*ReleaseBedRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{18}
}

func (x *ReleaseBedRequest) GetBedId() string {
	if x != nil {
		return x.BedId
	}
	return ""
}

type ReleaseBedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bed *Bed `protobuf:"bytes,1,opt,name=bed,proto3" json:"bed,omitempty"`
}

func (x *ReleaseBedResponse) Reset() {
	*x = ReleaseBedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReleaseBedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseBedResponse) ProtoMessage() {}

func (x *ReleaseBedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseBedResponse.ProtoReflect.Descriptor instead.
func (*ReleaseBedResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{19}
}

func (x *ReleaseBedResponse) GetBed() *Bed {
	if x != nil {
		return x.Bed
	}
	return nil
}

// RESERVE BED
type ReserveBedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BedId     string `protobuf:"bytes,1,opt,name=bed_id,json=bedId,proto3" json:"bed_id,omitempty"`
	PatientId string `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
}

func (x *ReserveBedRequest) Reset() {
	*x = ReserveBedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveBedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveBedRequest) ProtoMessage() {}

func (x *ReserveBedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveBedRequest.ProtoReflect.Descriptor instead.
func (*ReserveBedRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{20}
}

func (x *ReserveBedRequest) GetBedId() string {
	if x != nil {
		return x.BedId
	}
	return ""
}

func (x *ReserveBedRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type ReserveBedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bed *Bed `protobuf:"bytes,1,opt,name=bed,proto3" json:"bed,omitempty"`
}

func (x *ReserveBedResponse) Reset() {
	*x = ReserveBedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveBedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveBedResponse) ProtoMessage() {}

func (x *ReserveBedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveBedResponse.ProtoReflect.Descriptor instead.
func (*ReserveBedResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{21}
}

func (x *ReserveBedResponse) GetBed() *Bed {
	if x != nil {
		return x.Bed
	}
	return nil
}

// GET BY ID
type GetBedByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BedId string `protobuf:"bytes,1,opt,name=bed_id,json=bedId,proto3" json:"bed_id,omitempty"`
}

func (x *GetBedByIdRequest) Reset() {
	*x = GetBedByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBedByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBedByIdRequest) ProtoMessage() {}

func (x *GetBedByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBedByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBedByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetBedByIdRequest) GetBedId() string {
	if x != nil {
		return x.BedId
	}
	return ""
}

type GetBedByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bed *Bed `protobuf:"bytes,1,opt,name=bed,proto3" json:"bed,omitempty"`
}

func (x *GetBedByIdResponse) Reset() {
	*x = GetBedByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBedByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBedByIdResponse) ProtoMessage() {}

func (x *GetBedByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBedByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBedByIdResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{23}
}

func (x *GetBedByIdResponse) GetBed() *Bed {
	if x != nil {
		return x.Bed
	}
	return nil
}

// LIST
type ListBedsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status  BedStatus `protobuf:"varint,1,opt,name=status,proto3,enum=BedStatus" json:"status,omitempty"`
	BedType string    `protobuf:"bytes,2,opt,name=bed_type,json=bedType,proto3" json:"bed_type,omitempty"` //filter by bed type (ICU, General..)
	Page    int32     `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit   int32     `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *ListBedsRequest) Reset() {
	*x = ListBedsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBedsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBedsRequest) ProtoMessage() {}

func (x *ListBedsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBedsRequest.ProtoReflect.Descriptor instead.
func (*ListBedsRequest) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{24}
}

func (x *ListBedsRequest) GetStatus() BedStatus {
	if x != nil {
		return x.Status
	}
	return BedStatus_BED_AVAILABLE
}

func (x *ListBedsRequest) GetBedType() string {
	if x != nil {
		return x.BedType
	}
	return ""
}

func (x *ListBedsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBedsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListBedsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beds       []*Bed `protobuf:"bytes,1,rep,name=beds,proto3" json:"beds,omitempty"`
	TotalCount int32  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListBedsResponse) Reset() {
	*x = ListBedsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBedsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBedsResponse) ProtoMessage() {}

func (x *ListBedsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBedsResponse.ProtoReflect.Descriptor instead.
func (*ListBedsResponse) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{25}
}

func (x *ListBedsResponse) GetBeds() []*Bed {
	if x != nil {
		return x.Beds
	}
	return nil
}

func (x *ListBedsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type Timestamps3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Timestamps3) Reset() {
	*x = Timestamps3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timestamps3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamps3) ProtoMessage() {}

func (x *Timestamps3) ProtoReflect() protoreflect.Message {
	mi := &file_protos_nurse_service_nurse_service_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamps3.ProtoReflect.Descriptor instead.
func (*Timestamps3) Descriptor() ([]byte, []int) {
	return file_protos_nurse_service_nurse_service_proto_rawDescGZIP(), []int{26}
}

func (x *Timestamps3) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Timestamps3) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_protos_nurse_service_nurse_service_proto protoreflect.FileDescriptor

var file_protos_nurse_service_nurse_service_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x04, 0x0a, 0x0c,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x72, 0x74, 0x68, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x12, 0x3f, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x44, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x64, 0x6f, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x65,
	0x6c, 0x69, 0x67, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69,
	0x73, 0x45, 0x6c, 0x69, 0x67, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x46, 0x0a, 0x11, 0x6c, 0x61, 0x73,
	0x74, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x75, 0x70, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x68, 0x65, 0x61,
	0x6c, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0f,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x73, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x73, 0x33, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x73, 0x22, 0xc3, 0x01, 0x0a, 0x03, 0x42, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x65, 0x64,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62,
	0x65, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x65, 0x64, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x65, 0x64, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x42, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x0a, 0x0a, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x33, 0x52, 0x0a, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x22, 0xbd, 0x02, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69, 0x72, 0x74, 0x68, 0x5f, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74,
	0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x68, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3a, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23,
	0x0a, 0x05, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x05, 0x64, 0x6f,
	0x6e, 0x6f, 0x72, 0x22, 0x25, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3b, 0x0a, 0x14, 0x47, 0x65,
	0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72,
	0x52, 0x05, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x22, 0xb3, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1f, 0x0a,
	0x0b, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x23,
	0x0a, 0x0d, 0x6f, 0x6e, 0x6c, 0x79, 0x5f, 0x65, 0x6c, 0x69, 0x67, 0x69, 0x62, 0x6c, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x6f, 0x6e, 0x6c, 0x79, 0x45, 0x6c, 0x69, 0x67, 0x69,
	0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x60, 0x0a,
	0x12, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x44,
	0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x08, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0xcd, 0x02, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73,
	0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x69,
	0x72, 0x74, 0x68, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x62, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6c, 0x6f,
	0x6f, 0x64, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x62, 0x6c, 0x6f, 0x6f, 0x64, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67,
	0x68, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x68, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x5f, 0x63, 0x6f, 0x6e,
	0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x68,
	0x65, 0x61, 0x6c, 0x74, 0x68, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x3a, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x05, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x44,
	0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x05, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x12, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x2d, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x61, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x6f, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x64,
	0x6f, 0x6e, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64,
	0x6f, 0x6e, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x11, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0xa3, 0x01, 0x0a, 0x18, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x44, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x3f, 0x0a, 0x0d, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x0c, 0x6c, 0x61, 0x73, 0x74, 0x44, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x64, 0x6f, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x65,
	0x6c, 0x69, 0x67, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69,
	0x73, 0x45, 0x6c, 0x69, 0x67, 0x69, 0x62, 0x6c, 0x65, 0x22, 0x33, 0x0a, 0x16, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x6f, 0x6e, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x82,
	0x01, 0x0a, 0x17, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x11, 0x6c, 0x61,
	0x73, 0x74, 0x5f, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x0f, 0x6c, 0x61, 0x73, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x75, 0x70, 0x44, 0x61,
	0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x73, 0x5f, 0x65, 0x6c, 0x69, 0x67, 0x69, 0x62, 0x6c,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x45, 0x6c, 0x69, 0x67, 0x69,
	0x62, 0x6c, 0x65, 0x22, 0x51, 0x0a, 0x19, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x42, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x62, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x62, 0x65, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x1a, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x42, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x62, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x04, 0x2e, 0x42, 0x65, 0x64, 0x52, 0x03, 0x62, 0x65, 0x64, 0x22, 0x2a, 0x0a, 0x11,
	0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x42, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x62, 0x65, 0x64, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x42, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x03, 0x62, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x42, 0x65,
	0x64, 0x52, 0x03, 0x62, 0x65, 0x64, 0x22, 0x49, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x42, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62,
	0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x65, 0x64,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x22, 0x2c, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x42, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x03, 0x62, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x42, 0x65, 0x64, 0x52, 0x03, 0x62, 0x65, 0x64, 0x22,
	0x2a, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x65, 0x64, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x62, 0x65, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x65, 0x64, 0x49, 0x64, 0x22, 0x2c, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x42, 0x65, 0x64, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x03, 0x62, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x04,
	0x2e, 0x42, 0x65, 0x64, 0x52, 0x03, 0x62, 0x65, 0x64, 0x22, 0x7a, 0x0a, 0x0f, 0x4c, 0x69, 0x73,
	0x74, 0x42, 0x65, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x42,
	0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x62, 0x65, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x62, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x4d, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x64,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x04, 0x62, 0x65, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x04, 0x2e, 0x42, 0x65, 0x64, 0x52, 0x04, 0x62,
	0x65, 0x64, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x73, 0x33, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12,
	0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x2a, 0x57, 0x0a, 0x09, 0x42, 0x65,
	0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x45, 0x44, 0x5f, 0x41,
	0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x00, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x45,
	0x44, 0x5f, 0x4f, 0x43, 0x43, 0x55, 0x50, 0x49, 0x45, 0x44, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c,
	0x42, 0x45, 0x44, 0x5f, 0x52, 0x45, 0x53, 0x45, 0x52, 0x56, 0x45, 0x44, 0x10, 0x02, 0x12, 0x13,
	0x0a, 0x0f, 0x42, 0x45, 0x44, 0x5f, 0x4d, 0x41, 0x49, 0x4e, 0x54, 0x45, 0x4e, 0x41, 0x4e, 0x43,
	0x45, 0x10, 0x03, 0x32, 0xec, 0x05, 0x0a, 0x0c, 0x4e, 0x75, 0x72, 0x73, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f,
	0x6e, 0x6f, 0x72, 0x12, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x42, 0x79, 0x49, 0x64, 0x12, 0x14,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x73, 0x12, 0x12, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x6f,
	0x72, 0x12, 0x13, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x12, 0x13, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x14, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x6e, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x12, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x42, 0x65, 0x64, 0x12, 0x1a, 0x2e, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x42, 0x65,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x42, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65,
	0x42, 0x65, 0x64, 0x12, 0x12, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x42, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73,
	0x65, 0x42, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x42, 0x65, 0x64, 0x12, 0x12, 0x2e, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x42, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x42, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x65, 0x64, 0x42, 0x79, 0x49,
	0x64, 0x12, 0x12, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x64, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x65, 0x64, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x10, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x65, 0x64, 0x73, 0x42, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x64, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x11, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x65, 0x64, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x10, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44,
	0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x44, 0x6f, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x6f, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x75, 0x70, 0x12,
	0x17, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x75,
	0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6e, 0x75, 0x72, 0x73, 0x65, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_nurse_service_nurse_service_proto_rawDescOnce sync.Once
	file_protos_nurse_service_nurse_service_proto_rawDescData = file_protos_nurse_service_nurse_service_proto_rawDesc
)

func file_protos_nurse_service_nurse_service_proto_rawDescGZIP() []byte {
	file_protos_nurse_service_nurse_service_proto_rawDescOnce.Do(func() {
		file_protos_nurse_service_nurse_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_nurse_service_nurse_service_proto_rawDescData)
	})
	return file_protos_nurse_service_nurse_service_proto_rawDescData
}

var file_protos_nurse_service_nurse_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_nurse_service_nurse_service_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_protos_nurse_service_nurse_service_proto_goTypes = []any{
	(BedStatus)(0),                     // 0: BedStatus
	(*PatientDonor)(nil),               // 1: PatientDonor
	(*Bed)(nil),                        // 2: Bed
	(*CreateDonorRequest)(nil),         // 3: CreateDonorRequest
	(*CreateDonorResponse)(nil),        // 4: CreateDonorResponse
	(*GetDonorByIdRequest)(nil),        // 5: GetDonorByIdRequest
	(*GetDonorByIdResponse)(nil),       // 6: GetDonorByIdResponse
	(*ListDonorsRequest)(nil),          // 7: ListDonorsRequest
	(*ListDonorsResponse)(nil),         // 8: ListDonorsResponse
	(*UpdateDonorRequest)(nil),         // 9: UpdateDonorRequest
	(*UpdateDonorResponse)(nil),        // 10: UpdateDonorResponse
	(*DeleteDonorRequest)(nil),         // 11: DeleteDonorRequest
	(*DeleteDonorResponse)(nil),        // 12: DeleteDonorResponse
	(*RegisterDonationRequest)(nil),    // 13: RegisterDonationRequest
	(*RegisterDonationResponse)(nil),   // 14: RegisterDonationResponse
	(*RegisterCheckupRequest)(nil),     // 15: RegisterCheckupRequest
	(*RegisterCheckupResponse)(nil),    // 16: RegisterCheckupResponse
	(*AssignPatientToBedRequest)(nil),  // 17: AssignPatientToBedRequest
	(*AssignPatientToBedResponse)(nil), // 18: AssignPatientToBedResponse
	(*ReleaseBedRequest)(nil),          // 19: ReleaseBedRequest
	(*ReleaseBedResponse)(nil),         // 20: ReleaseBedResponse
	(*ReserveBedRequest)(nil),          // 21: ReserveBedRequest
	(*ReserveBedResponse)(nil),         // 22: ReserveBedResponse
	(*GetBedByIdRequest)(nil),          // 23: GetBedByIdRequest
	(*GetBedByIdResponse)(nil),         // 24: GetBedByIdResponse
	(*ListBedsRequest)(nil),            // 25: ListBedsRequest
	(*ListBedsResponse)(nil),           // 26: ListBedsResponse
	(*Timestamps3)(nil),                // 27: Timestamps3
	(*timestamppb.Timestamp)(nil),      // 28: google.protobuf.Timestamp
}
var file_protos_nurse_service_nurse_service_proto_depIdxs = []int32{
	28, // 0: PatientDonor.last_donation:type_name -> google.protobuf.Timestamp
	28, // 1: PatientDonor.last_checkup_date:type_name -> google.protobuf.Timestamp
	27, // 2: PatientDonor.timestamps:type_name -> Timestamps3
	0,  // 3: Bed.status:type_name -> BedStatus
	27, // 4: Bed.timestamps:type_name -> Timestamps3
	1,  // 5: CreateDonorResponse.donor:type_name -> PatientDonor
	1,  // 6: GetDonorByIdResponse.donor:type_name -> PatientDonor
	1,  // 7: ListDonorsResponse.patients:type_name -> PatientDonor
	1,  // 8: UpdateDonorResponse.donor:type_name -> PatientDonor
	28, // 9: RegisterDonationResponse.last_donation:type_name -> google.protobuf.Timestamp
	28, // 10: RegisterCheckupResponse.last_checkup_date:type_name -> google.protobuf.Timestamp
	2,  // 11: AssignPatientToBedResponse.bed:type_name -> Bed
	2,  // 12: ReleaseBedResponse.bed:type_name -> Bed
	2,  // 13: ReserveBedResponse.bed:type_name -> Bed
	2,  // 14: GetBedByIdResponse.bed:type_name -> Bed
	0,  // 15: ListBedsRequest.status:type_name -> BedStatus
	2,  // 16: ListBedsResponse.beds:type_name -> Bed
	28, // 17: Timestamps3.created_at:type_name -> google.protobuf.Timestamp
	28, // 18: Timestamps3.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 19: NurseService.CreateDonor:input_type -> CreateDonorRequest
	5,  // 20: NurseService.GetDonorById:input_type -> GetDonorByIdRequest
	7,  // 21: NurseService.ListDonors:input_type -> ListDonorsRequest
	9,  // 22: NurseService.UpdateDonor:input_type -> UpdateDonorRequest
	11, // 23: NurseService.DeleteDonor:input_type -> DeleteDonorRequest
	17, // 24: NurseService.AssignPatientToBed:input_type -> AssignPatientToBedRequest
	19, // 25: NurseService.ReleaseBed:input_type -> ReleaseBedRequest
	21, // 26: NurseService.ReserveBed:input_type -> ReserveBedRequest
	23, // 27: NurseService.GetBedById:input_type -> GetBedByIdRequest
	25, // 28: NurseService.ListBedsByStatus:input_type -> ListBedsRequest
	13, // 29: NurseService.RegisterDonation:input_type -> RegisterDonationRequest
	15, // 30: NurseService.RegisterCheckup:input_type -> RegisterCheckupRequest
	4,  // 31: NurseService.CreateDonor:output_type -> CreateDonorResponse
	6,  // 32: NurseService.GetDonorById:output_type -> GetDonorByIdResponse
	8,  // 33: NurseService.ListDonors:output_type -> ListDonorsResponse
	10, // 34: NurseService.UpdateDonor:output_type -> UpdateDonorResponse
	12, // 35: NurseService.DeleteDonor:output_type -> DeleteDonorResponse
	18, // 36: NurseService.AssignPatientToBed:output_type -> AssignPatientToBedResponse
	20, // 37: NurseService.ReleaseBed:output_type -> ReleaseBedResponse
	22, // 38: NurseService.ReserveBed:output_type -> ReserveBedResponse
	24, // 39: NurseService.GetBedById:output_type -> GetBedByIdResponse
	26, // 40: NurseService.ListBedsByStatus:output_type -> ListBedsResponse
	14, // 41: NurseService.RegisterDonation:output_type -> RegisterDonationResponse
	16, // 42: NurseService.RegisterCheckup:output_type -> RegisterCheckupResponse
	31, // [31:43] is the sub-list for method output_type
	19, // [19:31] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_protos_nurse_service_nurse_service_proto_init() }
func file_protos_nurse_service_nurse_service_proto_init() {
	if File_protos_nurse_service_nurse_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_nurse_service_nurse_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PatientDonor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Bed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateDonorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateDonorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetDonorByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetDonorByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListDonorsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ListDonorsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDonorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateDonorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteDonorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteDonorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterDonationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterDonationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterCheckupRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RegisterCheckupResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*AssignPatientToBedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*AssignPatientToBedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*ReleaseBedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*ReleaseBedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*ReserveBedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*ReserveBedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*GetBedByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*GetBedByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[24].Exporter = func(v any, i int) any {
			switch v := v.(*ListBedsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[25].Exporter = func(v any, i int) any {
			switch v := v.(*ListBedsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_nurse_service_nurse_service_proto_msgTypes[26].Exporter = func(v any, i int) any {
			switch v := v.(*Timestamps3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_nurse_service_nurse_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_nurse_service_nurse_service_proto_goTypes,
		DependencyIndexes: file_protos_nurse_service_nurse_service_proto_depIdxs,
		EnumInfos:         file_protos_nurse_service_nurse_service_proto_enumTypes,
		MessageInfos:      file_protos_nurse_service_nurse_service_proto_msgTypes,
	}.Build()
	File_protos_nurse_service_nurse_service_proto = out.File
	file_protos_nurse_service_nurse_service_proto_rawDesc = nil
	file_protos_nurse_service_nurse_service_proto_goTypes = nil
	file_protos_nurse_service_nurse_service_proto_depIdxs = nil
}
