// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.0
// source: protos/pharmacist-service/pharmacist-service.proto

package pharmacistpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MedicineStatus int32

const (
	MedicineStatus_MEDICINE_STATUS_UNSPECIFIED  MedicineStatus = 0
	MedicineStatus_MEDICINE_STATUS_AVAILABLE    MedicineStatus = 1
	MedicineStatus_MEDICINE_STATUS_OUT_OF_STOCK MedicineStatus = 2
	MedicineStatus_MEDICINE_STATUS_EXPIRED      MedicineStatus = 3
	MedicineStatus_MEDICINE_STATUS_DISCONTINUED MedicineStatus = 4
)

// Enum value maps for MedicineStatus.
var (
	MedicineStatus_name = map[int32]string{
		0: "MEDICINE_STATUS_UNSPECIFIED",
		1: "MEDICINE_STATUS_AVAILABLE",
		2: "MEDICINE_STATUS_OUT_OF_STOCK",
		3: "MEDICINE_STATUS_EXPIRED",
		4: "MEDICINE_STATUS_DISCONTINUED",
	}
	MedicineStatus_value = map[string]int32{
		"MEDICINE_STATUS_UNSPECIFIED":  0,
		"MEDICINE_STATUS_AVAILABLE":    1,
		"MEDICINE_STATUS_OUT_OF_STOCK": 2,
		"MEDICINE_STATUS_EXPIRED":      3,
		"MEDICINE_STATUS_DISCONTINUED": 4,
	}
)

func (x MedicineStatus) Enum() *MedicineStatus {
	p := new(MedicineStatus)
	*p = x
	return p
}

func (x MedicineStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MedicineStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_pharmacist_service_pharmacist_service_proto_enumTypes[0].Descriptor()
}

func (MedicineStatus) Type() protoreflect.EnumType {
	return &file_protos_pharmacist_service_pharmacist_service_proto_enumTypes[0]
}

func (x MedicineStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MedicineStatus.Descriptor instead.
func (MedicineStatus) EnumDescriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{0}
}

type Medicine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category    string         `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description string         `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price       float32        `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Company     string         `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	Status      MedicineStatus `protobuf:"varint,7,opt,name=status,proto3,enum=MedicineStatus" json:"status,omitempty"`
	Timestamps  *Timestamps5   `protobuf:"bytes,8,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
}

func (x *Medicine) Reset() {
	*x = Medicine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Medicine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Medicine) ProtoMessage() {}

func (x *Medicine) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Medicine.ProtoReflect.Descriptor instead.
func (*Medicine) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{0}
}

func (x *Medicine) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Medicine) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Medicine) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Medicine) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Medicine) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Medicine) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *Medicine) GetStatus() MedicineStatus {
	if x != nil {
		return x.Status
	}
	return MedicineStatus_MEDICINE_STATUS_UNSPECIFIED
}

func (x *Medicine) GetTimestamps() *Timestamps5 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type MedicineCategory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Timestamps  *Timestamps5 `protobuf:"bytes,5,opt,name=timestamps,proto3" json:"timestamps,omitempty"`
}

func (x *MedicineCategory) Reset() {
	*x = MedicineCategory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MedicineCategory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedicineCategory) ProtoMessage() {}

func (x *MedicineCategory) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedicineCategory.ProtoReflect.Descriptor instead.
func (*MedicineCategory) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{1}
}

func (x *MedicineCategory) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MedicineCategory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MedicineCategory) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MedicineCategory) GetTimestamps() *Timestamps5 {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

// ---------------- Medicine CRUD ----------------
// CREATE
type CreateMedicineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category    string         `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description string         `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       float32        `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	Company     string         `protobuf:"bytes,5,opt,name=company,proto3" json:"company,omitempty"`
	Status      MedicineStatus `protobuf:"varint,6,opt,name=status,proto3,enum=MedicineStatus" json:"status,omitempty"`
}

func (x *CreateMedicineRequest) Reset() {
	*x = CreateMedicineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMedicineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMedicineRequest) ProtoMessage() {}

func (x *CreateMedicineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMedicineRequest.ProtoReflect.Descriptor instead.
func (*CreateMedicineRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMedicineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMedicineRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateMedicineRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMedicineRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateMedicineRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CreateMedicineRequest) GetStatus() MedicineStatus {
	if x != nil {
		return x.Status
	}
	return MedicineStatus_MEDICINE_STATUS_UNSPECIFIED
}

type CreateMedicineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medicine *Medicine `protobuf:"bytes,1,opt,name=medicine,proto3" json:"medicine,omitempty"`
}

func (x *CreateMedicineResponse) Reset() {
	*x = CreateMedicineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMedicineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMedicineResponse) ProtoMessage() {}

func (x *CreateMedicineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMedicineResponse.ProtoReflect.Descriptor instead.
func (*CreateMedicineResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMedicineResponse) GetMedicine() *Medicine {
	if x != nil {
		return x.Medicine
	}
	return nil
}

// GET BY ID
type GetMedicineByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMedicineByIdRequest) Reset() {
	*x = GetMedicineByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedicineByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedicineByIdRequest) ProtoMessage() {}

func (x *GetMedicineByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedicineByIdRequest.ProtoReflect.Descriptor instead.
func (*GetMedicineByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetMedicineByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMedicineByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medicine *Medicine `protobuf:"bytes,1,opt,name=medicine,proto3" json:"medicine,omitempty"`
}

func (x *GetMedicineByIdResponse) Reset() {
	*x = GetMedicineByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedicineByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedicineByIdResponse) ProtoMessage() {}

func (x *GetMedicineByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedicineByIdResponse.ProtoReflect.Descriptor instead.
func (*GetMedicineByIdResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetMedicineByIdResponse) GetMedicine() *Medicine {
	if x != nil {
		return x.Medicine
	}
	return nil
}

// LIST
type ListMedicinesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search string         `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`                      // name, category, company
	Status MedicineStatus `protobuf:"varint,2,opt,name=status,proto3,enum=MedicineStatus" json:"status,omitempty"` // optional filter (available, out_of_stock)
	Page   int32          `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // for pagination
	Limit  int32          `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`                       // for pagination
}

func (x *ListMedicinesRequest) Reset() {
	*x = ListMedicinesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMedicinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMedicinesRequest) ProtoMessage() {}

func (x *ListMedicinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMedicinesRequest.ProtoReflect.Descriptor instead.
func (*ListMedicinesRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListMedicinesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListMedicinesRequest) GetStatus() MedicineStatus {
	if x != nil {
		return x.Status
	}
	return MedicineStatus_MEDICINE_STATUS_UNSPECIFIED
}

func (x *ListMedicinesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMedicinesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMedicinesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medicines  []*Medicine `protobuf:"bytes,1,rep,name=medicines,proto3" json:"medicines,omitempty"`
	TotalCount int32       `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // umumiy soni
}

func (x *ListMedicinesResponse) Reset() {
	*x = ListMedicinesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMedicinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMedicinesResponse) ProtoMessage() {}

func (x *ListMedicinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMedicinesResponse.ProtoReflect.Descriptor instead.
func (*ListMedicinesResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListMedicinesResponse) GetMedicines() []*Medicine {
	if x != nil {
		return x.Medicines
	}
	return nil
}

func (x *ListMedicinesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// UPDATE
type UpdateMedicineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category    string         `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Description string         `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price       float32        `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Company     string         `protobuf:"bytes,6,opt,name=company,proto3" json:"company,omitempty"`
	Status      MedicineStatus `protobuf:"varint,7,opt,name=status,proto3,enum=MedicineStatus" json:"status,omitempty"`
}

func (x *UpdateMedicineRequest) Reset() {
	*x = UpdateMedicineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMedicineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedicineRequest) ProtoMessage() {}

func (x *UpdateMedicineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedicineRequest.ProtoReflect.Descriptor instead.
func (*UpdateMedicineRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateMedicineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMedicineRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMedicineRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateMedicineRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMedicineRequest) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateMedicineRequest) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *UpdateMedicineRequest) GetStatus() MedicineStatus {
	if x != nil {
		return x.Status
	}
	return MedicineStatus_MEDICINE_STATUS_UNSPECIFIED
}

type UpdateMedicineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Medicine *Medicine `protobuf:"bytes,1,opt,name=medicine,proto3" json:"medicine,omitempty"`
}

func (x *UpdateMedicineResponse) Reset() {
	*x = UpdateMedicineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMedicineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedicineResponse) ProtoMessage() {}

func (x *UpdateMedicineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedicineResponse.ProtoReflect.Descriptor instead.
func (*UpdateMedicineResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateMedicineResponse) GetMedicine() *Medicine {
	if x != nil {
		return x.Medicine
	}
	return nil
}

// DELETE
type DeleteMedicineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMedicineRequest) Reset() {
	*x = DeleteMedicineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMedicineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedicineRequest) ProtoMessage() {}

func (x *DeleteMedicineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedicineRequest.ProtoReflect.Descriptor instead.
func (*DeleteMedicineRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteMedicineRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMedicineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 204 = deleted
}

func (x *DeleteMedicineResponse) Reset() {
	*x = DeleteMedicineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMedicineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedicineResponse) ProtoMessage() {}

func (x *DeleteMedicineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedicineResponse.ProtoReflect.Descriptor instead.
func (*DeleteMedicineResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteMedicineResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// ---------------- Medicine Category CRUD ----------------
// CREATE
type CreateMedicineCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreateMedicineCategoryRequest) Reset() {
	*x = CreateMedicineCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMedicineCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMedicineCategoryRequest) ProtoMessage() {}

func (x *CreateMedicineCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMedicineCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateMedicineCategoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{12}
}

func (x *CreateMedicineCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMedicineCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateMedicineCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category *MedicineCategory `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *CreateMedicineCategoryResponse) Reset() {
	*x = CreateMedicineCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateMedicineCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMedicineCategoryResponse) ProtoMessage() {}

func (x *CreateMedicineCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMedicineCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateMedicineCategoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateMedicineCategoryResponse) GetCategory() *MedicineCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

// GET BY ID
type GetMedicineCategoryByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetMedicineCategoryByIdRequest) Reset() {
	*x = GetMedicineCategoryByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedicineCategoryByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedicineCategoryByIdRequest) ProtoMessage() {}

func (x *GetMedicineCategoryByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedicineCategoryByIdRequest.ProtoReflect.Descriptor instead.
func (*GetMedicineCategoryByIdRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetMedicineCategoryByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMedicineCategoryByIdResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category *MedicineCategory `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *GetMedicineCategoryByIdResponse) Reset() {
	*x = GetMedicineCategoryByIdResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMedicineCategoryByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedicineCategoryByIdResponse) ProtoMessage() {}

func (x *GetMedicineCategoryByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedicineCategoryByIdResponse.ProtoReflect.Descriptor instead.
func (*GetMedicineCategoryByIdResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{15}
}

func (x *GetMedicineCategoryByIdResponse) GetCategory() *MedicineCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

// LIST
type ListMedicineCategoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search string `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"` //name
	Page   int32  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`    // for pagination
	Limit  int32  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`  // for pagination
}

func (x *ListMedicineCategoriesRequest) Reset() {
	*x = ListMedicineCategoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMedicineCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMedicineCategoriesRequest) ProtoMessage() {}

func (x *ListMedicineCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMedicineCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListMedicineCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListMedicineCategoriesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListMedicineCategoriesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMedicineCategoriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMedicineCategoriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Categories []*MedicineCategory `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	TotalCount int64               `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
}

func (x *ListMedicineCategoriesResponse) Reset() {
	*x = ListMedicineCategoriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListMedicineCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMedicineCategoriesResponse) ProtoMessage() {}

func (x *ListMedicineCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMedicineCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListMedicineCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListMedicineCategoriesResponse) GetCategories() []*MedicineCategory {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *ListMedicineCategoriesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// UPDATE
type UpdateMedicineCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *UpdateMedicineCategoryRequest) Reset() {
	*x = UpdateMedicineCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMedicineCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedicineCategoryRequest) ProtoMessage() {}

func (x *UpdateMedicineCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedicineCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateMedicineCategoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateMedicineCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMedicineCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMedicineCategoryRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateMedicineCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category *MedicineCategory `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
}

func (x *UpdateMedicineCategoryResponse) Reset() {
	*x = UpdateMedicineCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateMedicineCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMedicineCategoryResponse) ProtoMessage() {}

func (x *UpdateMedicineCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMedicineCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateMedicineCategoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateMedicineCategoryResponse) GetCategory() *MedicineCategory {
	if x != nil {
		return x.Category
	}
	return nil
}

// DELETE
type DeleteMedicineCategoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteMedicineCategoryRequest) Reset() {
	*x = DeleteMedicineCategoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMedicineCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedicineCategoryRequest) ProtoMessage() {}

func (x *DeleteMedicineCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedicineCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteMedicineCategoryRequest) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteMedicineCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMedicineCategoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // 204 = deleted
}

func (x *DeleteMedicineCategoryResponse) Reset() {
	*x = DeleteMedicineCategoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteMedicineCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedicineCategoryResponse) ProtoMessage() {}

func (x *DeleteMedicineCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedicineCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteMedicineCategoryResponse) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteMedicineCategoryResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type Timestamps5 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Timestamps5) Reset() {
	*x = Timestamps5{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Timestamps5) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamps5) ProtoMessage() {}

func (x *Timestamps5) ProtoReflect() protoreflect.Message {
	mi := &file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamps5.ProtoReflect.Descriptor instead.
func (*Timestamps5) Descriptor() ([]byte, []int) {
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP(), []int{22}
}

func (x *Timestamps5) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Timestamps5) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_protos_pharmacist_service_pharmacist_service_proto protoreflect.FileDescriptor

var file_protos_pharmacist_service_pharmacist_service_proto_rawDesc = []byte{
	0x0a, 0x32, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63,
	0x69, 0x73, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x70, 0x68, 0x61, 0x72,
	0x6d, 0x61, 0x63, 0x69, 0x73, 0x74, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69,
	0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x2c, 0x0a,
	0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x35, 0x52,
	0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x22, 0x86, 0x01, 0x0a, 0x10,
	0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x73, 0x35, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x3f, 0x0a, 0x16, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65,
	0x52, 0x08, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x40, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63,
	0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x25, 0x0a, 0x08, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x6d, 0x65,
	0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69,
	0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x61, 0x0a, 0x15, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e,
	0x65, 0x52, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xd2, 0x01,
	0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69,
	0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x27, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x4d, 0x65, 0x64, 0x69,
	0x63, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x22, 0x3f, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69,
	0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x08,
	0x6d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x08, 0x6d, 0x65, 0x64, 0x69, 0x63,
	0x69, 0x6e, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64,
	0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x16,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x55,
	0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x1e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x65, 0x64, 0x69,
	0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x08, 0x63, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x30, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64,
	0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49,
	0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x50, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x08, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x61, 0x0a, 0x1d, 0x4c, 0x69,
	0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x61,
	0x72, 0x63, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x74, 0x0a,
	0x1e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x31, 0x0a, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x65, 0x0a, 0x1d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64,
	0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x1e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x08,
	0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x22, 0x2f, 0x0a, 0x1d, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x38, 0x0a, 0x1e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x83, 0x01, 0x0a, 0x0b, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x73, 0x35, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x2a, 0xb1, 0x01, 0x0a,
	0x0e, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x1f, 0x0a, 0x1b, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x1d, 0x0a, 0x19, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x41, 0x56, 0x41, 0x49, 0x4c, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x01, 0x12,
	0x20, 0x0a, 0x1c, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x4f, 0x55, 0x54, 0x5f, 0x4f, 0x46, 0x5f, 0x53, 0x54, 0x4f, 0x43, 0x4b, 0x10,
	0x02, 0x12, 0x1b, 0x0a, 0x17, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x5f, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03, 0x12, 0x20,
	0x0a, 0x1c, 0x4d, 0x45, 0x44, 0x49, 0x43, 0x49, 0x4e, 0x45, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x44, 0x49, 0x53, 0x43, 0x4f, 0x4e, 0x54, 0x49, 0x4e, 0x55, 0x45, 0x44, 0x10, 0x04,
	0x32, 0xac, 0x06, 0x0a, 0x11, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x73, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x17, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64, 0x12, 0x17, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63,
	0x69, 0x6e, 0x65, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3e, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x73,
	0x12, 0x15, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65,
	0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e,
	0x65, 0x12, 0x16, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69,
	0x63, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64,
	0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d,
	0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12,
	0x1e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65,
	0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x5c, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1f, 0x2e, 0x47, 0x65,
	0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72,
	0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x47,
	0x65, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59,
	0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61,
	0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1e, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4d,
	0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x16, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67,
	0x6f, 0x72, 0x79, 0x12, 0x1e, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69,
	0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69,
	0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65,
	0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1e,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4d, 0x65, 0x64, 0x69, 0x63, 0x69, 0x6e, 0x65, 0x43,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x68,
	0x61, 0x72, 0x6d, 0x61, 0x63, 0x69, 0x73, 0x74, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protos_pharmacist_service_pharmacist_service_proto_rawDescOnce sync.Once
	file_protos_pharmacist_service_pharmacist_service_proto_rawDescData = file_protos_pharmacist_service_pharmacist_service_proto_rawDesc
)

func file_protos_pharmacist_service_pharmacist_service_proto_rawDescGZIP() []byte {
	file_protos_pharmacist_service_pharmacist_service_proto_rawDescOnce.Do(func() {
		file_protos_pharmacist_service_pharmacist_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_pharmacist_service_pharmacist_service_proto_rawDescData)
	})
	return file_protos_pharmacist_service_pharmacist_service_proto_rawDescData
}

var file_protos_pharmacist_service_pharmacist_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_pharmacist_service_pharmacist_service_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_protos_pharmacist_service_pharmacist_service_proto_goTypes = []any{
	(MedicineStatus)(0),                     // 0: MedicineStatus
	(*Medicine)(nil),                        // 1: Medicine
	(*MedicineCategory)(nil),                // 2: MedicineCategory
	(*CreateMedicineRequest)(nil),           // 3: CreateMedicineRequest
	(*CreateMedicineResponse)(nil),          // 4: CreateMedicineResponse
	(*GetMedicineByIdRequest)(nil),          // 5: GetMedicineByIdRequest
	(*GetMedicineByIdResponse)(nil),         // 6: GetMedicineByIdResponse
	(*ListMedicinesRequest)(nil),            // 7: ListMedicinesRequest
	(*ListMedicinesResponse)(nil),           // 8: ListMedicinesResponse
	(*UpdateMedicineRequest)(nil),           // 9: UpdateMedicineRequest
	(*UpdateMedicineResponse)(nil),          // 10: UpdateMedicineResponse
	(*DeleteMedicineRequest)(nil),           // 11: DeleteMedicineRequest
	(*DeleteMedicineResponse)(nil),          // 12: DeleteMedicineResponse
	(*CreateMedicineCategoryRequest)(nil),   // 13: CreateMedicineCategoryRequest
	(*CreateMedicineCategoryResponse)(nil),  // 14: CreateMedicineCategoryResponse
	(*GetMedicineCategoryByIdRequest)(nil),  // 15: GetMedicineCategoryByIdRequest
	(*GetMedicineCategoryByIdResponse)(nil), // 16: GetMedicineCategoryByIdResponse
	(*ListMedicineCategoriesRequest)(nil),   // 17: ListMedicineCategoriesRequest
	(*ListMedicineCategoriesResponse)(nil),  // 18: ListMedicineCategoriesResponse
	(*UpdateMedicineCategoryRequest)(nil),   // 19: UpdateMedicineCategoryRequest
	(*UpdateMedicineCategoryResponse)(nil),  // 20: UpdateMedicineCategoryResponse
	(*DeleteMedicineCategoryRequest)(nil),   // 21: DeleteMedicineCategoryRequest
	(*DeleteMedicineCategoryResponse)(nil),  // 22: DeleteMedicineCategoryResponse
	(*Timestamps5)(nil),                     // 23: Timestamps5
	(*timestamppb.Timestamp)(nil),           // 24: google.protobuf.Timestamp
}
var file_protos_pharmacist_service_pharmacist_service_proto_depIdxs = []int32{
	0,  // 0: Medicine.status:type_name -> MedicineStatus
	23, // 1: Medicine.timestamps:type_name -> Timestamps5
	23, // 2: MedicineCategory.timestamps:type_name -> Timestamps5
	0,  // 3: CreateMedicineRequest.status:type_name -> MedicineStatus
	1,  // 4: CreateMedicineResponse.medicine:type_name -> Medicine
	1,  // 5: GetMedicineByIdResponse.medicine:type_name -> Medicine
	0,  // 6: ListMedicinesRequest.status:type_name -> MedicineStatus
	1,  // 7: ListMedicinesResponse.medicines:type_name -> Medicine
	0,  // 8: UpdateMedicineRequest.status:type_name -> MedicineStatus
	1,  // 9: UpdateMedicineResponse.medicine:type_name -> Medicine
	2,  // 10: CreateMedicineCategoryResponse.category:type_name -> MedicineCategory
	2,  // 11: GetMedicineCategoryByIdResponse.category:type_name -> MedicineCategory
	2,  // 12: ListMedicineCategoriesResponse.categories:type_name -> MedicineCategory
	2,  // 13: UpdateMedicineCategoryResponse.category:type_name -> MedicineCategory
	24, // 14: Timestamps5.created_at:type_name -> google.protobuf.Timestamp
	24, // 15: Timestamps5.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 16: PharmacistService.CreateMedicine:input_type -> CreateMedicineRequest
	5,  // 17: PharmacistService.GetMedicineById:input_type -> GetMedicineByIdRequest
	7,  // 18: PharmacistService.ListMedicines:input_type -> ListMedicinesRequest
	9,  // 19: PharmacistService.UpdateMedicine:input_type -> UpdateMedicineRequest
	11, // 20: PharmacistService.DeleteMedicine:input_type -> DeleteMedicineRequest
	13, // 21: PharmacistService.CreateMedicineCategory:input_type -> CreateMedicineCategoryRequest
	15, // 22: PharmacistService.GetMedicineCategoryById:input_type -> GetMedicineCategoryByIdRequest
	17, // 23: PharmacistService.ListMedicineCategories:input_type -> ListMedicineCategoriesRequest
	19, // 24: PharmacistService.UpdateMedicineCategory:input_type -> UpdateMedicineCategoryRequest
	21, // 25: PharmacistService.DeleteMedicineCategory:input_type -> DeleteMedicineCategoryRequest
	4,  // 26: PharmacistService.CreateMedicine:output_type -> CreateMedicineResponse
	6,  // 27: PharmacistService.GetMedicineById:output_type -> GetMedicineByIdResponse
	8,  // 28: PharmacistService.ListMedicines:output_type -> ListMedicinesResponse
	10, // 29: PharmacistService.UpdateMedicine:output_type -> UpdateMedicineResponse
	12, // 30: PharmacistService.DeleteMedicine:output_type -> DeleteMedicineResponse
	14, // 31: PharmacistService.CreateMedicineCategory:output_type -> CreateMedicineCategoryResponse
	16, // 32: PharmacistService.GetMedicineCategoryById:output_type -> GetMedicineCategoryByIdResponse
	18, // 33: PharmacistService.ListMedicineCategories:output_type -> ListMedicineCategoriesResponse
	20, // 34: PharmacistService.UpdateMedicineCategory:output_type -> UpdateMedicineCategoryResponse
	22, // 35: PharmacistService.DeleteMedicineCategory:output_type -> DeleteMedicineCategoryResponse
	26, // [26:36] is the sub-list for method output_type
	16, // [16:26] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_protos_pharmacist_service_pharmacist_service_proto_init() }
func file_protos_pharmacist_service_pharmacist_service_proto_init() {
	if File_protos_pharmacist_service_pharmacist_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Medicine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*MedicineCategory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMedicineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMedicineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetMedicineByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetMedicineByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*ListMedicinesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*ListMedicinesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMedicineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMedicineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMedicineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMedicineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMedicineCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*CreateMedicineCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*GetMedicineCategoryByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*GetMedicineCategoryByIdResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*ListMedicineCategoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*ListMedicineCategoriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMedicineCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateMedicineCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMedicineCategoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*DeleteMedicineCategoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_pharmacist_service_pharmacist_service_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*Timestamps5); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_pharmacist_service_pharmacist_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_pharmacist_service_pharmacist_service_proto_goTypes,
		DependencyIndexes: file_protos_pharmacist_service_pharmacist_service_proto_depIdxs,
		EnumInfos:         file_protos_pharmacist_service_pharmacist_service_proto_enumTypes,
		MessageInfos:      file_protos_pharmacist_service_pharmacist_service_proto_msgTypes,
	}.Build()
	File_protos_pharmacist_service_pharmacist_service_proto = out.File
	file_protos_pharmacist_service_pharmacist_service_proto_rawDesc = nil
	file_protos_pharmacist_service_pharmacist_service_proto_goTypes = nil
	file_protos_pharmacist_service_pharmacist_service_proto_depIdxs = nil
}
