CREATE TABLE IF NOT EXISTS donors(
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name TEXT NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) UNIQUE NOT NULL,
    address TEXT NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    gender gender_type NOT NULL,
    birth_date DATE NOT NULL,
    blood_group blood_type NOT NULL,
    weight SMALLINT NOT NULL,
    health_condition health_condition_type NOT NULL,
    last_donation TIMESTAMP,
    donation_count INT DEFAULT 0,
    last_checkup_date TIMESTAMP,
    donation_location TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
);