// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package storage

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createMedicine = `-- name: CreateMedicine :one

INSERT INTO medicines
    (
        name,
        category,
        description,
        price,
        company,
        status
    )
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
    id, 
    name,
    category,
    description,
    price,
    company,
    status,
    created_at,
    updated_at
`

type CreateMedicineParams struct {
	Name        string
	Category    MedicineCategory
	Description string
	Price       float64
	Company     string
	Status      MedicineStatus
}

type CreateMedicineRow struct {
	ID          uuid.UUID
	Name        string
	Category    MedicineCategory
	Description string
	Price       float64
	Company     string
	Status      MedicineStatus
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

// -------------- Medicine CRUD ----------------
func (q *Queries) CreateMedicine(ctx context.Context, arg CreateMedicineParams) (CreateMedicineRow, error) {
	row := q.db.QueryRowContext(ctx, createMedicine,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Price,
		arg.Company,
		arg.Status,
	)
	var i CreateMedicineRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Price,
		&i.Company,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMedicine = `-- name: DeleteMedicine :exec
UPDATE medicines
SET deleted_at = $2
WHERE id = $1
`

type DeleteMedicineParams struct {
	ID        uuid.UUID
	DeletedAt sql.NullTime
}

func (q *Queries) DeleteMedicine(ctx context.Context, arg DeleteMedicineParams) error {
	_, err := q.db.ExecContext(ctx, deleteMedicine, arg.ID, arg.DeletedAt)
	return err
}

const getMedicineById = `-- name: GetMedicineById :one
SELECT 
    id,
    name,
    category,
    description,
    company,
    status,
    price,
    created_at,
    updated_at
FROM 
    medicines
WHERE id=$1
    AND deleted_at IS NULL
`

type GetMedicineByIdRow struct {
	ID          uuid.UUID
	Name        string
	Category    MedicineCategory
	Description string
	Company     string
	Status      MedicineStatus
	Price       float64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

func (q *Queries) GetMedicineById(ctx context.Context, id uuid.UUID) (GetMedicineByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getMedicineById, id)
	var i GetMedicineByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Company,
		&i.Status,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMedicines = `-- name: ListMedicines :many
SELECT
    id,
    name,
    category,
    description,
    company,
    status,
    price,
    created_at,
    updated_at,
    COUNT(*) OVER() AS total_count  -- total count filtering boyicha
FROM
    medicines
WHERE deleted_at IS NULL
    AND (
        $1::text=''  -- :text - frontenddan kelgan parametr. '' bolsa, barcha datalarni qaytaradi. Agar bosh bolmasa name, category, company ustunlarida qidirishni boshlaydi.
        OR LOWER(name) LIKE LOWER(CONCAT('%', $1::text, '%')) --LOWER - barcha harflarni kichkina qilib oladi. 
        OR LOWER(category) LIKE LOWER(CONCAT('%', $1::text, '%')) -- CONCAT('%', :search, '%') - example: %aspirin% qilib qidiradi, yani matn ichida qayerdan bolmasin topadi.
        OR LOWER(company) LIKE LOWER(CONCAT('%', $1::text, '%'))
    )
    AND ($2::status IS NULL OR status = $2::status) -- agar stus NULL bolsa barcha yozuvlar olinadi, bolmasa taqqoslaydi.
ORDER BY
    created_at DESC -- yaratilgan sana boyicha teskari tartibda chiqaradi, natijada eng yangilari birinchi chiqadi.
LIMIT $3 -- faqat n ta row olinadi
OFFSET ($4 - 1) * $3
`

type ListMedicinesParams struct {
	Column1 string
	Column2 interface{}
	Limit   int32
	Column4 interface{}
}

type ListMedicinesRow struct {
	ID          uuid.UUID
	Name        string
	Category    MedicineCategory
	Description string
	Company     string
	Status      MedicineStatus
	Price       float64
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	TotalCount  int64
}

func (q *Queries) ListMedicines(ctx context.Context, arg ListMedicinesParams) ([]ListMedicinesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMedicines,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMedicinesRow
	for rows.Next() {
		var i ListMedicinesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Company,
			&i.Status,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMedicine = `-- name: UpdateMedicine :one

UPDATE medicines
SET
    name = $2,
    category = $3,
    description = $4,
    price = $5,
    company = $6,
    status = $7,
    updated_at = $8
WHERE id = $1
    AND deleted_at IS NULL
RETURNING
    id, 
    name,
    category,
    description,
    price,
    company,
    status,
    created_at,
    updated_at
`

type UpdateMedicineParams struct {
	ID          uuid.UUID
	Name        string
	Category    MedicineCategory
	Description string
	Price       float64
	Company     string
	Status      MedicineStatus
	UpdatedAt   sql.NullTime
}

type UpdateMedicineRow struct {
	ID          uuid.UUID
	Name        string
	Category    MedicineCategory
	Description string
	Price       float64
	Company     string
	Status      MedicineStatus
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

// m ta row o‘tkazib, keyingilarini oladi
func (q *Queries) UpdateMedicine(ctx context.Context, arg UpdateMedicineParams) (UpdateMedicineRow, error) {
	row := q.db.QueryRowContext(ctx, updateMedicine,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Description,
		arg.Price,
		arg.Company,
		arg.Status,
		arg.UpdatedAt,
	)
	var i UpdateMedicineRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Price,
		&i.Company,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
