CREATE TYPE medicine_category AS ENUM (
    'MEDICINE_CATEGORY_UNSPECIFIED',
    'MEDICINE_CATEGORY_ANTIBIOTIC',
    'MEDICINE_CATEGORY_ANALGESIC',
    'MEDICINE_CATEGORY_ANTIVIRAL',
    'MEDICINE_CATEGORY_VITAMINS',
    'MEDICINE_CATEGORY_ANTIFUNGAL',
    'MEDICINE_CATEGORY_VACCINE',
    'MEDICINE_CATEGORY_OTHER'
);

CREATE TYPE medicine_status AS ENUM (
    'MEDICINE_STATUS_UNSPECIFIED',
    'MEDICINE_STATUS_AVAILABLE',
    'MEDICINE_STATUS_OUT_OF_STOCK',
    'MEDICINE_STATUS_EXPIRED',
    'MEDICINE_STATUS_DISCONTINUED'
);
